"""remove is active from  the category

Revision ID: ef657890145c
Revises: a9a1e27ba40d
Create Date: 2025-08-26 18:20:45.860576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef657890145c'
down_revision: Union[str, Sequence[str], None] = 'a9a1e27ba40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_active')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
